#!/bin/bash
mongoimport -u root -p devpass --authenticationDatabase=admin --host clearance-db --port 27017 --db clearance_service --collection assignment_requests --file ./e2e-database/clearance-db/clearance_service.assignment_requests.json --jsonArray --mode=upsert
mongoimport -u root -p devpass --authenticationDatabase=admin --host clearance-db --port 27017 --db clearance_service --collection audit --file ./e2e-database/clearance-db/clearance_service.audit.json --jsonArray --mode=upsert
mongoimport -u root -p devpass --authenticationDatabase=admin --host clearance-db --port 27017 --db clearance_service --collection clearance_assignment --file ./e2e-database/clearance-db/clearance_service.clearance_assignment.json --jsonArray --mode=upsert
mongoimport -u root -p devpass --authenticationDatabase=admin --host clearance-db --port 27017 --db clearance_service --collection clearance --file ./e2e-database/clearance-db/clearance_service.clearance.json --jsonArray --mode=upsert
mongoimport -u root -p devpass --authenticationDatabase=admin --host clearance-db --port 27017 --db clearance_service --collection email_templates --file ./e2e-database/clearance-db/clearance_service.email_templates.json --jsonArray --mode=upsert
mongoimport -u root -p devpass --authenticationDatabase=admin --host clearance-db --port 27017 --db clearance_service --collection legacy_liaison --file ./e2e-database/clearance-db/clearance_service.legacy_liaison.json --jsonArray --mode=upsert
mongoimport -u root -p devpass --authenticationDatabase=admin --host clearance-db --port 27017 --db clearance_service --collection liaison_authorized_clearances --file ./e2e-database/clearance-db/clearance_service.liaison_authorized_clearances.json --jsonArray --mode=upsert
mongoimport -u root -p devpass --authenticationDatabase=admin --host clearance-db --port 27017 --db clearance_service --collection liaison_clearance_mapping --file ./e2e-database/clearance-db/clearance_service.liaison_clearance_mapping.json --jsonArray --mode=upsert
mongoimport -u root -p devpass --authenticationDatabase=admin --host clearance-db --port 27017 --db clearance_service --collection liaison_master --file ./e2e-database/clearance-db/clearance_service.liaison_master.json --jsonArray --mode=upsert
mongoimport -u root -p devpass --authenticationDatabase=admin --host clearance-db --port 27017 --db clearance_service --collection liaison-clearance-permissions --file ./e2e-database/clearance-db/clearance_service.liaison-clearance-permissions.json --jsonArray --mode=upsert
mongoimport -u root -p devpass --authenticationDatabase=admin --host clearance-db --port 27017 --db clearance_service --collection liaison --file ./e2e-database/clearance-db/clearance_service.liaison.json --jsonArray --mode=upsert
mongoimport -u root -p devpass --authenticationDatabase=admin --host clearance-db --port 27017 --db clearance_service --collection scheduled_action --file ./e2e-database/clearance-db/clearance_service.scheduled_action.json --jsonArray --mode=upsert
echo "Database was restored!"