import os
from dataclasses import dataclass

C9K_PAGE_SIZE = 100
C9K_CLEARANCE_LIMIT = 40
C9K_BASE_URL = os.getenv("CCURE_BASE_URL")
C9K_TIMEOUT = 3

C9K_USERNAME = os.getenv("CCURE_USERNAME")
C9K_PASSWORD = os.getenv("CCURE_PASSWORD")
C9K_CLIENT_NAME = os.getenv("CCURE_CLIENT_NAME")
C9K_CLIENT_VERSION = os.getenv("CCURE_CLIENT_VERSION")
C9K_CLIENT_ID = os.getenv("CCURE_CLIENT_ID")

LIAISON_ACKNOWLEDGEMENT_DAYS = int(os.getenv("LIAISON_ACKNOWLEDGEMENT_DAYS", "60"))

DEVELOPMENT = "t" in os.getenv("DEVELOPMENT", "true").lower()
SCHEDULE_CLEARANCES = "t" in os.getenv("SCHEDULE_CLEARANCES", "true").lower()
SCHEDULER_LIMIT = int(os.getenv("SCHEDULER_LIMIT", 40))
PURGE_OLD_SCHEDULED_ACTIONS = "t" in os.getenv("PURGE_OLD_SCHEDULED_ACTIONS", "true").lower()
SCHEDULED_ACTION_PURGE_CUTOFF = int(os.getenv("SCHEDULED_ACTION_PURGE_CUTOFF", 90))
